FROM apache/airflow:2.10.4-python3.10

# Copy requirements.txt into the image
COPY fastapi_app/requirements.txt /requirements.txt

# Switch to airflow user before installing packages
USER airflow

# Install packages
RUN pip install --no-cache-dir -r /requirements.txt

# Switch back to root if needed later, otherwise leave as airflow
USER root
